[package]
name = "hex_gfx"
version = "0.0.1"
edition = "2021"

[dependencies]
hex_win = { path = "../win", version = "0.0.1" }
hex_math = { path = "../math", version = "0.0.1" }

[build-dependencies]
bindgen = "^0.69.1"
