[package]
name = "hex_io"
version = "0.0.1"
description = "Window and input library for hexn"
authors = [ "Zeno343 <zacheryklinglesmith@gmail.com" ]
repository = "https://github.com/Zeno343/hexn.git"
license = "MIT"

[build-dependencies]
bindgen = "^0.69.1"
